<?php 


?>
<html>
<head>
   <title>High Wycombe Map</title>
   
   <link rel="stylesheet" href="leaflet/leaflet.css" />
   <!--[if lte IE 8]><link rel="stylesheet" href="leaflet/leaflet.ie.css" /><![endif]-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
	 <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
	 <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
	<link rel="stylesheet" href="leaflet/leaflet-routing-machine.css" />
	<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
	<script src="leaflet/leaflet-routing-machine.js"></script>
   
   <script src="leaflet/leaflet.js"></script>
   
   <script language="javascript">
      function init() {
		  <?php 
		 include 'latlong1.php';
		 ?>
         var map = new L.Map('map');                       
                
      	 L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
            maxZoom: 18
         }).addTo(map);
         map.attributionControl.setPrefix(''); // Don't show the 'Powered by Leaflet' text.

         var highwycombe = new L.LatLng(51.627186, -0.752795); 
         map.setView(highwycombe, 15);
         
         // Define an array. This could be done in a seperate js file.
         // This tidy formatted section could even be generated by a server-side script
         // or fetched seperately as a jsonp request.
		 
		 //var markers = "<?php echo $data; ?>";
		 
		 
		 
         //var markers = [
           // [ -0.1244324, 51.5006728, "Big Ben" ],
            //[ -0.119623, 51.503308, "London Eye" ],
            //[ -0.1279688, 51.5077286, "Nelson's Column<br><a href=\"https://en.wikipedia.org/wiki/Nelson's_Column\">wp</a>" ] 
         //];
		 //var polyline = L.polyline(latlong).addTo(map);
         
         //Loop through the markers array
         for (var i=0; i<latlong.length; i++) {
           
            var lat = latlong[i][0];
            var lon = latlong[i][1];
            //var popupText = markers[i][2];
            
             var markerLocation = new L.LatLng(lat, lon);
             var marker = new L.Marker(markerLocation);
             map.addLayer(marker);
         
             //marker.bindPopup(popupText);
         
         }

      }
   </script>
   
</head>
<body onLoad="javascript:init();">
   <div id="map" style="height: 700px"></div>
   <div id="explanation"></a>
   </div>
</body>                                                                                                                          
</html>
<?php ?>
